/*
 * This file is generated by jOOQ.
*/
package org.redlich.pubs.model;


import javax.annotation.Generated;

import org.redlich.pubs.model.tables.Authors;
import org.redlich.pubs.model.tables.Publications;
import org.redlich.pubs.model.tables.Publishers;
import org.redlich.pubs.model.tables.States;
import org.redlich.pubs.model.tables.Types;


/**
 * Convenience access to all tables in pubs
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pubs.authors</code>.
     */
    public static final Authors AUTHORS = org.redlich.pubs.model.tables.Authors.AUTHORS;

    /**
     * The table <code>pubs.publications</code>.
     */
    public static final Publications PUBLICATIONS = org.redlich.pubs.model.tables.Publications.PUBLICATIONS;

    /**
     * The table <code>pubs.publishers</code>.
     */
    public static final Publishers PUBLISHERS = org.redlich.pubs.model.tables.Publishers.PUBLISHERS;

    /**
     * The table <code>pubs.states</code>.
     */
    public static final States STATES = org.redlich.pubs.model.tables.States.STATES;

    /**
     * The table <code>pubs.types</code>.
     */
    public static final Types TYPES = org.redlich.pubs.model.tables.Types.TYPES;
}
