/*
 * This file is generated by jOOQ.
*/
package org.redlich.pubs.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.redlich.pubs.model.tables.Publications;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PublicationsRecord extends UpdatableRecordImpl<PublicationsRecord> implements Record8<Long, Long, Long, String, Long, Long, Timestamp, String> {

    private static final long serialVersionUID = -1125440056;

    /**
     * Setter for <code>pubs.publications.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pubs.publications.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pubs.publications.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pubs.publications.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pubs.publications.type_id</code>.
     */
    public void setTypeId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pubs.publications.type_id</code>.
     */
    public Long getTypeId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pubs.publications.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pubs.publications.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pubs.publications.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>pubs.publications.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>pubs.publications.publisher_id</code>.
     */
    public void setPublisherId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>pubs.publications.publisher_id</code>.
     */
    public Long getPublisherId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>pubs.publications.publish_date</code>.
     */
    public void setPublishDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>pubs.publications.publish_date</code>.
     */
    public Timestamp getPublishDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>pubs.publications.url</code>.
     */
    public void setUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>pubs.publications.url</code>.
     */
    public String getUrl() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Long, String, Long, Long, Timestamp, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Long, String, Long, Long, Timestamp, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Publications.PUBLICATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Publications.PUBLICATIONS.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Publications.PUBLICATIONS.TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Publications.PUBLICATIONS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Publications.PUBLICATIONS.AUTHOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Publications.PUBLICATIONS.PUBLISHER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Publications.PUBLICATIONS.PUBLISH_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Publications.PUBLICATIONS.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getPublisherId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getPublishDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicationsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicationsRecord value2(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicationsRecord value3(Long value) {
        setTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicationsRecord value4(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicationsRecord value5(Long value) {
        setAuthorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicationsRecord value6(Long value) {
        setPublisherId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicationsRecord value7(Timestamp value) {
        setPublishDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicationsRecord value8(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicationsRecord values(Long value1, Long value2, Long value3, String value4, Long value5, Long value6, Timestamp value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PublicationsRecord
     */
    public PublicationsRecord() {
        super(Publications.PUBLICATIONS);
    }

    /**
     * Create a detached, initialised PublicationsRecord
     */
    public PublicationsRecord(Long id, Long version, Long typeId, String title, Long authorId, Long publisherId, Timestamp publishDate, String url) {
        super(Publications.PUBLICATIONS);

        set(0, id);
        set(1, version);
        set(2, typeId);
        set(3, title);
        set(4, authorId);
        set(5, publisherId);
        set(6, publishDate);
        set(7, url);
    }
}
